apiVersion : apps/v1
kind: Deployment
metadata:
  name: evansdokcerglpiap 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: evansdokcerglpiap
  template:
    metadata:
      labels:
        app: evansdokcerglpiap 
    spec:
      containers:
        - name: evansdokcerglpiap 
          image: eforder.azurecr.io/evansdokcerglpiap
          ports:
          - containerPort: 80